version: "3.9"
   
services:
  stripe:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to localhost:3000/api/webhooks/"
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    volumes:
      - ./stripe-config:/root/.config/stripe
  
    